name: Build Node.js Express

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Copy package.json
        run: |
          mkdir -p dist
          cp package.json dist/package.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: cd dist && npm run build
